INSERT INTO `pregunta` (`id`, `nombre`) VALUES (1, '¿Cuenta su ente territorial con información acerca de la población con discapacidad en edad escolar y en primera infancia?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (2, '¿Del total de los niños y niñas en edad escolar que asisten a la escuela regular, cuántos presentan alguna discapacidad? De qué tipo?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (3, '¿Cuáles políticas, planes o programas ha implementado su Administración que estén orientados a fomentar o apoyar el derecho a la educación de los niños y niñas con discapacidad a través de su asistencia, participación y promoción en la escuela regular?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (4, '¿Qué logros ha alcanzado como resultado de las estrategias de adopción de procesos de inclusión educativa (formación de docentes con enfoque inclusivo, dotación de materiales pertinentes - libros braille, audios, software, intérpretes-  y adecuación de la infraestructura educativa para que sea accesible)?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (5, '¿Cuál es su principal logro en esta materia? Y por qué?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (6, 'En caso de no haber implementado un sistema de educación regular, indique cuáles han sido las razones y/o obstáculos para iniciar el proceso.');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (7, 'Indicar y anexar presupuesto de las políticas, planes, programas o estrategias relacionadas con este tema.');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (8, 'Las personas con discapacidad participan de los programas de generación de ingresos y empleo que su gobierno ha diseñado para el resto de ciudadanos? Qué ajustes ha debido hacer para lograr esta participación efectiva de las personas con discapacidad en esos programas?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (9, '¿Qué estrategias ha implementado su Administración para  promover la vinculación laboral, el apoyo a proyectos productivos y la generación de ingreso de las personas con discapacidad?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (10, '¿Qué resultados ha alcanzado en esta materia?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (11, '¿Se le han presentado algunos obstáculos en este tema? ¿Cómo los ha solucionado?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (12, 'Se ha capacitado a los equipos de planeación y contratación en las normas de accesibilidad física de las personas con discapacidad?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (13, '¿De qué manera se verifica que las obras civiles, construcciones públicas o contratistas de su ente territorial cumplan con las normas de accesibilidad física?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (14, 'Los términos de referencia de obras civiles incluyen expresamente la necesidad de cumplir con las normas de accesibilidad?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (15, '¿Qué medidas se adoptan cuando estas normas no se cumplen?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (16, 'Son las instalaciones de su Administración accesibles para la población con discapacidad?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (17, 'Qué infraestructura pública local cuenta con rampas, baños accesibles, ascensor  y otros ajustes que favorezcan la inclusión? (bibliotecas, centros culturales, hospital, etc)');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (18, 'Existe algún mecanismo de orientación e información para las personas con discapacidad?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (19, 'Con cuáles mecanismos cuenta su Administración para garantizar el acceso a la información de las personas con discapacidad? (Braille, Intérprete  de lengua de señas, señales sonoras y visuales…)');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (20, 'Se consulta a la comunidad con discapacidad organizada para el diseño de sus políticas planes o programas en cada sector?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (21, 'Sus políticas locales ven a las personas con discapacidad con un enfoque asistencial, o de derechos? ¿Estas políticas tienen en cuenta la Convención de las Naciones Unidas para Personas con Discapacidad? ¿Cómo lo ha hecho?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (22, '¿Qué estrategias ha implementado su administración para lograr que las actividades culturales, recreativas y deportivas incluyan en su ente territorial a las personas con discapacidad con el resto de la comunidad?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (23, '¿Los centros deportivos, culturales y de recreación son accesibles?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (24, '¿Cuáles estrategias ha utilizado para la actualización y análisis de la información del Registro?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (25, '¿Cuál ha sido su estrategia para la difusión e incentivo a la vinculación de su comunidad con discapacidad al Registro de Localización y Caracterización de las personas con discapacidad?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (26, 'Qué herramientas ha empleado para consolidar el diagnóstico y conocimiento de las condiciones de vida de las personas con discapacidad de su municipio o departamento? ');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (27, '¿En qué otros sectores su Administración ha realizado programas o proyectos de inclusión social?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (28, '¿Qué logros ha obtenido en estos sectores?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (29, 'Describa una experiencia de inclusión social que haya sido adoptada por otro ente territorial o un proyecto que haya sido modelo a nivel departamental o nacional.');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (30, 'Describa una experiencia de inclusión social en la cual su Administración haya desarrollado herramientas, técnicas o procedimientos innovadores que le hayan permitido mejorar sus resultados.');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (31, '¿Cuál es el principal canal de participación de su ente territorial para los movimientos, organizaciones o personas con discapacidad?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (32, '¿Qué resultados ha alcanzado su Administración en cuanto a promover una efectiva participación de los movimientos, organizaciones o personas con discapacidad en los asuntos públicos?');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (33, 'Describa una experiencia de gestión integral con enfoque de inclusión social bajo los parámetros en los cuales se define este criterio en el formulario y señale las razones por las cuales las considera como buenas experiencias.');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (34, 'Nombre de la buena práctica');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (35, 'Sitio en el que se realizó la práctica');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (36, 'Impacto causado por la práctica');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (37, 'Personas beneficiarias');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (38, 'Costo de la práctica');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (39, 'Continuidad de la práctica');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (40, 'Dificultades que se presentaron y cómo se superaron en el desarrollo de la práctica');
INSERT INTO `pregunta` (`id`, `nombre`) VALUES (41, 'Participación de la comunidad en la práctica');
