INSERT INTO `subcategoria` (`id`, `nombre`) VALUES (1, 'Educación');
INSERT INTO `subcategoria` (`id`, `nombre`) VALUES (2, 'Mercado Laboral y Productividad');
INSERT INTO `subcategoria` (`id`, `nombre`) VALUES (3, 'Accesibilidad');
INSERT INTO `subcategoria` (`id`, `nombre`) VALUES (4, 'Acceso a la información');
INSERT INTO `subcategoria` (`id`, `nombre`) VALUES (5, 'Convivencia y Derechos Humanos');
INSERT INTO `subcategoria` (`id`, `nombre`) VALUES (6, 'Cultura, Recreación y Deporte');
INSERT INTO `subcategoria` (`id`, `nombre`) VALUES (7, 'Registro de localización y caracterización de personas con discapacidad');
INSERT INTO `subcategoria` (`id`, `nombre`) VALUES (8, 'Otros sectores');
INSERT INTO `subcategoria` (`id`, `nombre`) VALUES (9, 'Gestión Integral');
INSERT INTO `subcategoria` (`id`, `nombre`) VALUES (10, 'Replicabilidad');
INSERT INTO `subcategoria` (`id`, `nombre`) VALUES (11, 'Innovación');
INSERT INTO `subcategoria` (`id`, `nombre`) VALUES (12, 'Participación');
