INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (1, 'Bolívar', 13);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (2, 'Nariño', 52);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (3, 'Antioquia', 5);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (4, 'Atlántico', 8);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (5, 'Bogotá, D.C.', 11);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (6, 'Boyacá', 15);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (7, 'Caldas', 17);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (8, 'Caquetá', 18);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (9, 'Cauca', 19);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (10, 'Cesar', 20);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (11, 'Córdoba', 23);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (12, 'Cundinamarca', 25);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (13, 'Chocó', 27);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (14, 'Huila', 41);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (15, 'La Guajira', 44);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (16, 'Magdalena', 47);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (17, 'Meta', 50);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (18, 'Norte De Santander', 54);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (19, 'Quindio', 63);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (20, 'Risaralda', 66);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (21, 'Santander', 68);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (22, 'Sucre', 70);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (23, 'Tolima', 73);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (24, 'Valle Del Cauca', 76);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (25, 'Arauca', 81);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (26, 'Casanare', 85);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (27, 'Putumayo', 86);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (28, 'Archipiélago De San Andrés, Providencia Y Santa Catalina', 88);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (29, 'Amazonas', 91);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (30, 'Guainía', 94);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (31, 'Guaviare', 95);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (32, 'Vaupés', 97);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (33, 'Vichada', 99);
INSERT INTO `departamento` (`id`, `nombre`, `codigo`) VALUES (34, 'No Aplica', 0);
